version: "3"

services:
  node-app:
    build: .
    container_name: node-app
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=local
    volumes: 
      - ./src:/app/src
    ports:
      - 3000:3000
    command: "npm run dev"
    networks:
      - development

networks: 
  development:
      name: dev_network
